package com.kleiders.tpainting.paintings;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraft.world.entity.decoration.Motive;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD) public class paintingadds {

    @SubscribeEvent public static void registerMotives(RegistryEvent.Register<Motive> event) {
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_001"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_002"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_003"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_004"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_005"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_006"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_007"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_008"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_009"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_010"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_011"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_012"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_013"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_014"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_015"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_016"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_017"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_018"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_019"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_020"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_021"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_022"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_023"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_024"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_025"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_026"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_027"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_028"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_029"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_030"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_031"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_032"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_033"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_034"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_035"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_036"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_037"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_038"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_039"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_040"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_041"));
        event.getRegistry().register(new Motive(64, 48).setRegistryName("t_paint_042"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_001"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_002"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_003"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_004"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_005"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_006"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_007"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_008"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_009"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_010"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_011"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_012"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_013"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_014"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_015"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("tmid_paint_016"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_017"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_018"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_019"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_020"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_021"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_022"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_023"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_024"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_025"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_026"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tmid_paint_027"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("tmid_paint_028"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("tmid_paint_029"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("tmid_paint_030"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tall_paint_031"));
        event.getRegistry().register(new Motive(32, 32).setRegistryName("tall_paint_032"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_001"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_002"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_003"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_004"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_005"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_006"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_007"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_008"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_009"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_010"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_011"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_012"));
        event.getRegistry().register(new Motive(16, 32).setRegistryName("tall_paint_013"));
        event.getRegistry().register(new Motive(16, 16).setRegistryName("small_paint_001"));
        event.getRegistry().register(new Motive(16, 16).setRegistryName("small_paint_002"));
        event.getRegistry().register(new Motive(16, 16).setRegistryName("small_paint_003"));
        event.getRegistry().register(new Motive(16, 16).setRegistryName("small_paint_004"));
        event.getRegistry().register(new Motive(16, 16).setRegistryName("small_paint_005"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_001"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_002"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_003"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_004"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_005"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_006"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_007"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_008"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_009"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_010"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_011"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_012"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_013"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_014"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_015"));
        event.getRegistry().register(new Motive(32, 16).setRegistryName("plain_paint_016"));
    }

}

